Public Class FacturaModel
    Public Property NumeroFactura As String
    Public Property Campo0 As String
    Public Property Campo1 As String
    Public Property Campo2 As String
    Public Property Campo3 As String
    Public Property Campo4 As String
    Public Property Campo5 As String
    Public Property Campo6 As String
    Public Property Campo7 As String
    Public Property Campo8 As String
    Public Property Campo9 As String
    Public Property Campo10 As String
    Public Property Campo11 As String
    Public Property Campo12 As Decimal
    Public Property Campo13 As String
    Public Property Campo14 As String
    Public Property Campo15 As String
    Public Property Campo16 As String
    Public Property Campo17 As String
    Public Property Campo18 As String
    Public Property Campo19 As String
    Public Property Campo20 As String
    Public Property Campo21 As String
    Public Property Campo22 As String
    Public Property Campo23 As String
    Public Property Campo24 As String
    Public Property Campo25 As String
    Public Property Campo26 As String
    Public Property Campo27 As String
    Public Property Campo28 As String
    Public Property Campo29 As String
    Public Property Campo30 As String
    Public Property Campo31 As String
    Public Property Campo32 As String
    Public Property Campo33 As String
    Public Property Campo34 As String
    Public Property Campo35 As String
    Public Property Campo36 As String
    Public Property Campo37 As String
    Public Property Campo38 As String
    Public Property Campo39 As String
    Public Property Campo40 As String
    Public Property Campo41 As String
    Public Property Campo42 As String
    Public Property Campo43 As String
    Public Property Campo44 As String
    Public Property Campo45 As String
    Public Property Campo46 As String
    Public Property Campo47 As String
    Public Property Campo48 As String
    Public Property Campo49 As String
    Public Property Campo50 As String
    Public Property Campo51 As String
    Public Property Campo52 As String
    Public Property Campo53 As String
    Public Property Campo54 As Decimal
    Public Property Campo55 As Decimal
    Public Property Campo56 As String
    Public Property Campo57 As String
    Public Property Campo58 As String
    Public Property Campo59 As String
    Public Property Campo60 As String
    Public Property Campo61 As String
    Public Property Campo62 As String
    Public Property Campo63 As String
    Public Property Campo64 As String


End Class
